### ISSUE TITLE
Why? What? Who? How?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/flutter-phoenix-channels-demo#1]
We are building our backend in `Phoenix` as outlined in: https://github.com/dwyl/technology-stack#phoenix
We need to showcase how to interact with `Phoenix` from `Flutter` in the _simplest_ way possible. 

Currently `phoenix_socket`: https://pub.dev/packages/phoenix_socket 
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/194400/215789702-2028e906-7eb0-47b7-a15e-314b580b5e26.png">

Appears to be the best `<option>`. 💭 

Although the slow response rate on the open PRs: https://github.com/braverhealth/phoenix-socket-dart/pulls

<img width="1209" alt="image" src="https://user-images.githubusercontent.com/194400/216365984-8e175373-5700-4fb1-823b-f761106962d4.png">

Is less than reassuring... ⏳ 
e.g: https://github.com/braverhealth/phoenix-socket-dart/pull/55 should at least have a _comment_ by now ... 🤷‍♂️ 

`if` you find a _better_ one, please share. 🙏 
If you get stuck, take a look at: https://github.com/supabase/supabase-flutter#realtime-data-as-stream
Disect their code and if needed (comment first) build our own library to do this!

# Todo ✅ 

+ [x] Document _every_ step you take along the way in building this. 📝 
  it needs to be followed by someone whose time is _very_ scarce so [please don't skip any steps](https://github.com/dwyl/learn-flutter/issues/75) ... 🙏 
+ [x] Launch a basic `Phoenix` App that has a `channel`.
  + [x] A good _pre_-task would be to `UPDATE` our existing `phoenix-chat-example`. 
  please see: https://github.com/dwyl/phoenix-chat-example/issues/149
  and use that as the basis for this integration.
+ [x] Create a basic `Flutter` app 
   + [x] add `phoenix_socket` as a dependency.
+ [x] Run both on `localhost` and attempt to connect `Flutter` to `Phoenix`.
+ [x] Show "who is online" in the `Phoenix` App.
+ [x] Display this data in the `Flutter` App.
+ [x] **Bonus Level**: deploy the `Flutter` app to `Fly.io` as a `PWA` see: https://github.com/dwyl/learn-flutter/issues/9
  + [ ] Connect the deployed `Flutter` app to https://phoenix-chat.fly.dev to showcase the "Production" version. 🚀 

That's it. 

This should take a couple of days to document & build with tests in both `Phoenix` and `Flutter`.

Please leave a comment on this issue with ***`each`*** step you take in your quest. 
The resulting repo/demo should be easy for _anyone_ to run.
If you have _any_ questions, please comment. 
And if I take longer than **`T1h`** to respond on `GitHub` signal-message me with a direct link to the issue comment. 
e.g: https://github.com/dwyl/learn-flutter/issues/9#issuecomment-1413898764

**Comment by LuchoTurtle** [comment]
Just pushed the README sections with the tutorial. Not going to submit it for review yet because I want to:

- [x] add CI
- [x] check README for typos
- [x] add it to Fly.io through https://github.com/dwyl/learn-flutter/issues/9
- [x] keep custom commands on mix.exs
